### ISSUE TITLE
Error ketika gagal login

### ISSUE THREAD

**Issue by DSlite** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-database#1]
Kalau aku login menggunakan akun yang salah masih tidak ada handlernya, jadi masih ke "object not found", mungkin linknya masih salah. Mangat Rek!!
![image](https://user-images.githubusercontent.com/17781660/66973146-3b8d9680-f0c1-11e9-98ff-3c93197a3205.png)

**Comment by hisyamzf** [comment]
done
