### ISSUE TITLE
Session tidak ada

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-database#10]
Pada saat website di load yang tampil adalah index.html dan setelah login hanya berpindah ke index2.html dimana di index2.html itu sendiri tidak ada session sama sekali.

![Screen Shot 2019-10-18 at 15 16 58](https://user-images.githubusercontent.com/53895082/67077871-5859c500-f1ba-11e9-985b-0039e0895c0d.png)

**Comment by hisyamzf** [comment]
done
