### ISSUE TITLE
Saran, Menambahkan pemintas Home di Form Login/Register

### ISSUE THREAD

**Issue by Rezaaisyi** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-database#19]
![image](https://user-images.githubusercontent.com/55181853/68218932-b50d0a80-0017-11ea-859c-53c2cee2ac78.png)
selamat malam kawan, saya punya saran agar menambahkan pemintas ke index.php atau home dari form login atau register . Terima kasih

**Comment by hisyamzf** [comment]
siapp cak
