### ISSUE TITLE
Company and Fllow us menu 

### ISSUE THREAD

**Issue by MadeBy-Ali** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-database#3]
![1571296948977](https://user-images.githubusercontent.com/49668571/66986704-9aff9c80-f0e9-11e9-801d-a972fefa7619.jpg)

1. Typo di (Follow Us) menu 
2. Isi menu Company belum ada yang berfungsi  
Company
Home
Services
About
News
FAQ's
Contact

3. menu Fllow us belum berfungsi:
facebook 
twitter
linkdin
google

**Comment by lumbricina** [comment]
done. the contact page is still under construstion, but the link is done
