### ISSUE TITLE
Setelah Login tidak ada feature logout

### ISSUE THREAD

**Issue by MadeBy-Ali** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-database#4]
setelah berhasil regist dan login akan ke direct ke homepage tapi tidak ada feature logout

![messageImage_1571297473524](https://user-images.githubusercontent.com/49668571/66987423-f54d2d00-f0ea-11e9-8f90-ea6e46cf02ad.jpg)

**Comment by lumbricina** [comment]
sudah ada :) 
<img width="899" alt="4" src="https://user-images.githubusercontent.com/55181574/67261444-df64b100-f4ca-11e9-8fc8-2bacc388f09d.PNG">
