### ISSUE TITLE
page contact us pada bagian name, email, message, ga bisa dikirim, ga ada buttton send .

### ISSUE THREAD

**Issue by belladewusa** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-database#5]
![Screenshot (97)](https://user-images.githubusercontent.com/55181780/66987871-bc618800-f0eb-11e9-9634-6153c2c07142.png)

**Comment by lumbricina** [comment]
Thank You, The contact page is under construction :)

**Comment by lumbricina** [comment]
done
