### ISSUE TITLE
page contact us, button learn more sama all service ga berfungsi

### ISSUE THREAD

**Issue by belladewusa** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-database#6]
![Screenshot (98)](https://user-images.githubusercontent.com/55181780/66988275-735e0380-f0ec-11e9-89df-ad905499ab51.png)
![Screenshot (99)](https://user-images.githubusercontent.com/55181780/66988283-75c05d80-f0ec-11e9-89e8-579c2faf2cad.png)

**Comment by lumbricina** [comment]
done
