### ISSUE TITLE
page contact us, menu home, service, about dll ga ke link

### ISSUE THREAD

**Issue by NesyaKurnia** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-database#7]
pada page contact us, ada menu home, service, about, news, faq dan contact tidak ke link ke masing-masing sesuai buttonnya, tapi malah balik ke home. dan harus nya gaada button contact
![Screenshot (10)_LI](https://user-images.githubusercontent.com/50094449/66992037-52e57780-f0f3-11e9-8d8a-8429ae0fda27.jpg)

**Comment by lumbricina** [comment]
done. the contact page is under construction, but the link is done
