### ISSUE TITLE
Tulisan term of service tidak ada isinya

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-database#8]
Seharusnya ketika term of service di tekan maka akan memunculkan aturan-aturan yang harus di sanggupi oleh orang yang akan mendaftar.

![Screen Shot 2019-10-17 at 9 19 41 PM](https://user-images.githubusercontent.com/53895082/67017359-d919b200-f123-11e9-9451-eae6ef343b78.png)

**Comment by lumbricina** [comment]
solved!
<img width="904" alt="Capture" src="https://user-images.githubusercontent.com/55181574/67139063-f52d6880-f275-11e9-8a4f-51caa9790524.PNG">
