### ISSUE TITLE
Page sign in login with yang tidak ada link nya

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-database#9]
pada halaman login.html terdapat 3 logo untuk login namun semua tidak bisa di tekan dan tidak memunculkan suatu pop up page untuk login.

![Screen Shot 2019-10-17 at 9 22 20 PM](https://user-images.githubusercontent.com/53895082/67017629-3d3c7600-f124-11e9-99ef-07124504e9de.png)

**Comment by lumbricina** [comment]
solved !
<img width="657" alt="Capture" src="https://user-images.githubusercontent.com/55181574/67139121-8dc3e880-f276-11e9-863a-58bc5459a4f6.PNG">
